### ISSUE TITLE
AzureDirectory

### ISSUE THREAD

**Issue by kedigby** [Shazwazza/Examine#158]
I have tried setting up AzureDirectory with an existing master - slave configuration. 
Whilst the master node is happy and can write to blob storage, creating the index. The slave node will not start. 

This is the stack trace from the slave node:
```
2020-02-21 16:51:10,494 [P6632/D2/T1] WARN  Umbraco.Core.Sync.DatabaseServerMessenger - No last synced Id found, this generally means this is a new server/install. The server will build its caches and indexes, and then adjust its last synced Id to the latest found in the database and maintain cache updates based on that Id.
 2020-02-21 16:51:10,779 [P6632/D2/T1] WARN  umbraco.content - Failed to load Xml, file does not exist.
 2020-02-21 16:52:20,873 [P6632/D4/T17] ERROR Umbraco.Web.ExamineStartup - The index NewsIndexer is rebuilding due to being unreadable/corrupt
System.IO.FileNotFoundException: segments_4 ---> Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 677
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 604
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.FetchAttributes(AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlob.cs:line 1619
   at Examine.AzureDirectory.AzureDirectory.OpenInput(String name) in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine.AzureDirectory\AzureDirectory.cs:line 347
Request Information
RequestID:ace97bd9-b01e-0026-66d7-e8dbac000000
RequestDate:Fri, 21 Feb 2020 16:52:18 GMT
StatusMessage:The specified blob does not exist.
ErrorCode:BlobNotFound

   at Lucene.Net.Index.SegmentInfos.FindSegmentsFile.Run(IndexCommit commit)
   at Lucene.Net.Index.DirectoryReader.Open(Directory directory, IndexDeletionPolicy deletionPolicy, IndexCommit commit, Boolean readOnly, Int32 termInfosIndexDivisor)
   at Examine.LuceneEngine.Providers.LuceneIndexer.IsReadable(Exception& ex) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneIndexer.cs:line 968
 2020-02-21 16:52:50,382 [P6632/D4/T17] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.IO.FileNotFoundException: segments_4 ---> Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 677
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 604
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.FetchAttributes(AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlob.cs:line 1619
   at Examine.AzureDirectory.AzureDirectory.OpenInput(String name) in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine.AzureDirectory\AzureDirectory.cs:line 347
Request Information
RequestID:ace9c00b-b01e-0026-41d7-e8dbac000000
RequestDate:Fri, 21 Feb 2020 16:52:49 GMT
StatusMessage:The specified blob does not exist.
ErrorCode:BlobNotFound
```

The Appsettings are the same in the master and slave nodes, the slave has the following indexer setup:
```
<add name="NewsIndexer"
             type="UmbracoExamine.UmbracoContentIndexer, UmbracoExamine"
             dataService="UmbracoExamine.DataServices.UmbracoDataService, UmbracoExamine"
             indexSet="NewsIndexSet"
             supportUnpublished="false"
             supportProtected="false"
             analyzer="Lucene.Net.Analysis.Standard.StandardAnalyzer, Lucene.Net"
             enableDefaultEventHandler="true"
             directoryFactory="Examine.AzureDirectory.ReadOnlyAzureDirectoryFactory, Examine.AzureDirectory" />
```

Let me know if there is any more information that I can provide to help.

**Comment by sebaDem27** [comment]
Hello,

Do you find a solution because I have the same problem ?

Thanks

**Comment by Shazwazza** [comment]
Sorry for the delay, it looks to be the same/similar problem as just reported here https://github.com/Shazwazza/Examine/issues/160, i'll keep both issues open for now since they are different stack traces. I'll add some additional info to #160

**Comment by Shazwazza** [comment]
Closing due to being stale and out of date
