### ISSUE TITLE
Umbraoco BootFailedException: Access to the path write.lock is denied.

### ISSUE THREAD

**Issue by MihaiPotcoava** [Shazwazza/Examine#161]
Hi,

We're having issues with the live Umbraco instance, hosted in Azure:
-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.
-> System.UnauthorizedAccessException: Access to the path 'D:\home\site\wwwroot\App_Data\TEMP\ExamineIndexes\Internal\write.lock' is denied.

We're running Umbraco 8.5.3 and Examine 1.0.1.
We've followed the recommendations form:
https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/azure-web-apps

I guess this is happening when Azure is switching the website between web workers. 
The error above was thrown 3.6k times in a ~ 1minute window. 
In this window, the website was down, returning an error to the end-users.
After this window, the website was automatically restarted and everything worked.

Can you please help, this is very alarming for us since we couldn't find a solution and we're not sure when this can appear again.

Thanks!

**Comment by MihaiPotcoava** [comment]
Hi, just FYI we've upgraded to Umbraco 8.6.0 with examine 1.0.3

The problem above has been resolved but instead, we have another issue from time to time:
```
Inner Exception
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at Examine.LuceneEngine.Providers.LuceneIndex.SafelyProcessQueueItems(Action`1 onComplete) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneIndex.cs:line 783
   at Examine.LuceneEngine.Providers.LuceneIndex.PerformIndexItems(IEnumerable`1 values, Action`1 onComplete) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneIndex.cs:line 302
   at Umbraco.Examine.UmbracoContentIndex.PerformIndexItems(IEnumerable`1 values, Action`1 onComplete) in D:\a\1\s\src\Umbraco.Examine\UmbracoContentIndex.cs:line 102
   at Examine.Providers.BaseIndexProvider.IndexItems(IEnumerable`1 values) in C:\projects\examine-qvx04\src\Examine\Providers\BaseIndexProvider.cs:line 76
   at Umbraco.Web.Search.ExamineComponent.DeferedReIndexForContent.Execute(ExamineComponent examineComponent, IContent content, Boolean isPublished) in D:\a\1\s\src\Umbraco.Web\Search\ExamineComponent.cs:line 603
   at Umbraco.Web.Search.ExamineComponent.DeferedReIndexForContent.Execute() in D:\a\1\s\src\Umbraco.Web\Search\ExamineComponent.cs:line 598
   at Umbraco.Web.Search.ExamineComponent.DeferedActions.Execute() in D:\a\1\s\src\Umbraco.Web\Search\ExamineComponent.cs:line 572
   at Umbraco.Web.Search.ExamineComponent.DeferedActions.<>c.<Get>b__1_1(Boolean completed, DeferedActions actions) in D:\a\1\s\src\Umbraco.Web\Search\ExamineComponent.cs:line 561
   at Umbraco.Core.Scoping.ScopeContext.EnlistedObject`1.Execute(Boolean completed) in D:\a\1\s\src\Umbraco.Core\Scoping\ScopeContext.cs:line 69
   at Umbraco.Core.Scoping.ScopeContext.ScopeExit(Boolean completed) in D:\a\1\s\src\Umbraco.Core\Scoping\ScopeContext.cs:line 26
```

I'll open a separate issue for this

**Comment by Shazwazza** [comment]
8.6.4 will be out soon which contains some critical fixes which I believe is the source of your issue https://github.com/umbraco/Umbraco-CMS/issues?q=label%3Arelease%2F8.6.4+is%3Aclosed

The issue you've just mentioned also has links to the related issues.

I've also just added more checks for this error. It won't prevent the underlying problems that are occurring (due to Umbraco's management) but will prevent unhandled exceptions from occurring https://github.com/Shazwazza/Examine/issues/166

**Comment by lindeberg** [comment]
We just got a similar exception taking down live site as well

```
Boot failed: Umbraco cannot run. See Umbraco's log file for more details.
-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.
-> System.UnauthorizedAccessException: Access to the path 'D:\home\site\wwwroot\App_Data\TEMP\ExamineIndexes\UmbracoFormsRecords\write.lock' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at Lucene.Net.Store.SimpleFSLock.Release() in d:\Lucene.Net\FullRepo\trunk\src\core\Store\SimpleFSLockFactory.cs:line 204
   at Examine.LuceneEngine.Directories.MultiIndexLock.Release() in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\Directories\MultiIndexLock.cs:line 68
   at Umbraco.Forms.Core.Components.UmbracoFormsComponent.EnsureIndexIsUnlocked(IIndex index)
   at Umbraco.Forms.Core.Components.UmbracoFormsComponent.CreateAndRegisterExamineIndexes()
   at Umbraco.Forms.Core.Components.UmbracoFormsComponent.Initialize()
   at Umbraco.Core.Composing.ComponentCollection.Initialize()
   at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) 
```

**Comment by Shazwazza** [comment]
@lindeberg  That is an umbraco and or umbraco forms issue. You'll need to provide more details, version info, steps to replicate, config info, load balance info etc and report on the umbraco or forms issue tracker.
