### ISSUE TITLE
IndexOutOfRangeException taking down appdomain

### ISSUE THREAD

**Issue by Shazwazza** [Shazwazza/Examine#164]
It's possible that Lucene can take down the entire app domain with an unhandled exception that occurs on a background thread. The stack trace is:

```
System.IndexOutOfRangeException: Index of bound 0
   at Lucene.Net.Util.BitVector.GetAndSet(Int32 bit) in d:\Lucene.Net\FullRepo\trunk\src\core\Util\BitVector.cs:line 85
   at Lucene.Net.Index.SegmentReader.DoDelete(Int32 docNum) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\SegmentReader.cs:line 1143
   at Lucene.Net.Index.IndexReader.DeleteDocument(Int32 docNum) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\IndexReader.cs:line 985
   at Lucene.Net.Index.DocumentsWriter.ApplyDeletes(IndexReader reader, Int32 docIDStart) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\DocumentsWriter.cs:line 1324
   at Lucene.Net.Index.DocumentsWriter.ApplyDeletes(SegmentInfos infos) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\DocumentsWriter.cs:line 1268
   at Lucene.Net.Index.IndexWriter.ApplyDeletes() in d:\Lucene.Net\FullRepo\trunk\src\core\Index\IndexWriter.cs:line 5367
   at Lucene.Net.Index.IndexWriter.DoFlushInternal(Boolean flushDocStores, Boolean flushDeletes) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\IndexWriter.cs:line 4374
   at Lucene.Net.Index.IndexWriter.DoFlush(Boolean flushDocStores, Boolean flushDeletes) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\IndexWriter.cs:line 4197
   at Lucene.Net.Index.IndexWriter.PrepareCommit(IDictionary`2 commitUserData) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\IndexWriter.cs:line 4034
   at Lucene.Net.Index.IndexWriter.Commit(IDictionary`2 commitUserData) in d:\Lucene.Net\FullRepo\trunk\src\core\Index\IndexWriter.cs:line 4116
   at Examine.LuceneEngine.Providers.LuceneIndex.IndexCommiter.TimerRelease() in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneIndex.cs:line 1011
   at Examine.LuceneEngine.Providers.LuceneIndex.IndexCommiter.<ScheduleCommit>b__7_0(Object _) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneIndex.cs:line 963
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
```

**Comment by Shazwazza** [comment]
Not the same but slightly related to this one https://github.com/umbraco/Umbraco-CMS/issues/3683 Those errors/stack trace show that there's index corruption going on which is probably the case here too (i.e. perhaps the appdomain terminated unexpectedly and files weren't written correctly). 

Similar report is here https://our.umbraco.com/forum/using-umbraco-and-getting-started/94839-entire-site-has-a-503-error

Other similar issues are reported even by other Lucene based systems outside of Examine.

We should not let the appdomain die though.

**Comment by nickornotto** [comment]
In relation to this issue and the issue https://github.com/umbraco/Umbraco-CMS/issues/3683

After two months since the configuration change (described on umbraco forum: https://our.umbraco.com/forum/using-umbraco-and-getting-started/102097-whats-the-best-umbraco-websites-subdomains-and-indexes-configuration-to-avoid-lucene-errors#comment-322674) I can say that unfortunately it didn't solve the problem.

The exception started to appear much less but over the time it raises gradually and now sometimes we are execting almost the same intensity of the issue as before.

The indexes crash (and crash the entire website) even if there seem not to be any activity on the site but just upon saving a content in the CMS (clicking the Save content button).

**Comment by Shazwazza** [comment]
I have replied to the thread https://our.umbraco.com/forum/using-umbraco-and-getting-started/102097-whats-the-best-umbraco-websites-subdomains-and-indexes-configuration-to-avoid-lucene-errors#comment-322673

**Comment by Shazwazza** [comment]
Following up on this just posted this here for reference, someone has managed to capture a different log output of this sequence which is not being caught by the change made here:

```
Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess)
   at Lucene.Net.Store.SimpleFSDirectory+SimpleFSIndexOutput..ctor(System.IO.FileInfo)
   at Lucene.Net.Store.SimpleFSDirectory.CreateOutput(System.String)
   at Examine.LuceneEngine.Directories.SyncIndexOutput.Close()
   at Lucene.Net.Index.TermVectorsTermsWriter.CloseDocStore(Lucene.Net.Index.SegmentWriteState)
   at Lucene.Net.Index.TermsHash.CloseDocStore(Lucene.Net.Index.SegmentWriteState)
   at Lucene.Net.Index.TermsHash.CloseDocStore(Lucene.Net.Index.SegmentWriteState)
   at Lucene.Net.Index.DocInverter.CloseDocStore(Lucene.Net.Index.SegmentWriteState)
   at Lucene.Net.Index.DocFieldProcessor.CloseDocStore(Lucene.Net.Index.SegmentWriteState)
   at Lucene.Net.Index.DocumentsWriter.CloseDocStore()
   at Lucene.Net.Index.DocumentsWriter.Flush(Boolean)
   at Lucene.Net.Index.IndexWriter.DoFlushInternal(Boolean, Boolean)
   at Lucene.Net.Index.IndexWriter.DoFlush(Boolean, Boolean)
   at Lucene.Net.Index.IndexWriter.PrepareCommit(System.Collections.Generic.IDictionary`2<System.String,System.String>, Boolean)
   at Lucene.Net.Index.IndexWriter.Commit(System.Collections.Generic.IDictionary`2<System.String,System.String>)
   at Examine.LuceneEngine.Providers.LuceneIndexer+IndexCommiter.TimerRelease()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

The initial fix here was catching IndexOutOfRangeException but it seems that an IOException can also occur. It is still unclear how this can happen but it's obviously best to not kill the app domain so I'll update the check with catching all Exceptions to be safe.  I'll create a new issue in a bit after some more investigation.
