### ISSUE TITLE
NullReferenceException in GetFieldInternalQuery

### ISSUE THREAD

**Issue by Shazwazza** [Shazwazza/Examine#170]
Not sure how to replicate but have seen this stack trace which would be worth investigating

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Examine.LuceneEngine.Search.LuceneSearchQueryBase.GetFieldInternalQuery(String fieldName, IExamineValue fieldValue, Boolean useQueryParser) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Search\LuceneSearchQueryBase.cs:line 314
   at Examine.LuceneEngine.Search.LuceneSearchQueryBase.GetMultiFieldQuery(IReadOnlyList`1 fields, IReadOnlyList`1 fieldVals, Occur occurance, Boolean matchAllCombinations) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Search\LuceneSearchQueryBase.cs:line 469
   at Examine.LuceneEngine.Search.LuceneSearchQueryBase.GroupedOrInternal(String[] fields, IExamineValue[] fieldVals, Occur occurrence) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Search\LuceneSearchQueryBase.cs:line 246
   at Examine.LuceneEngine.Search.LuceneQuery.GroupedOr(IEnumerable`1 fields, IExamineValue[] query) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Search\LuceneQuery.cs:line 45
....
```

**Comment by Shazwazza** [comment]
Have added null checks in rev e899db654614a08988f8848922f25c26399c8b37
