### ISSUE TITLE
Indexwriter is closed error logs

### ISSUE THREAD

**Issue by Sven883** [Shazwazza/Examine#264]
Hello,

We're using examine v1.2.0 & umbraco v8.14.0.
Our logs are getting flooded with the following error: 

```
Lucene.Net.Store.AlreadyClosedException: this IndexWriter is closed
   at Lucene.Net.Index.IndexWriter.EnsureOpen(Boolean includePendingClose)
   at Lucene.Net.Index.IndexWriter.get_Directory()
   at Examine.LuceneEngine.Providers.LuceneSearcher.IndexExistsImpl()
   at Examine.LuceneEngine.Providers.LuceneSearcher.ValidateSearcher()
   at Examine.LuceneEngine.Providers.LuceneSearcher.GetLuceneSearcher()
   at Examine.LuceneEngine.Providers.LuceneSearcher.GetSearchContext()
   at Examine.LuceneEngine.Providers.BaseLuceneSearcher.CreateQuery(String category, BooleanOperation defaultOperation, Analyzer luceneAnalyzer, LuceneSearchOptions searchOptions)
   at Examine.LuceneEngine.Providers.BaseLuceneSearcher.CreateQuery(String category, BooleanOperation defaultOperation)
   at Intracto.Extensions.BLL.BlogLogic.GetBlogArticleIdByUrl(String url, String culture)
   at Intracto.Extensions.Provider.BlogArticleFinder.TryFindContent(PublishedRequest request)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Umbraco.Web.Routing.PublishedRouter.FindPublishedContent(PublishedRequest request)
   at Umbraco.Web.Routing.PublishedRouter.FindPublishedContentAndTemplate(PublishedRequest request)
   at Umbraco.Web.Routing.PublishedRouter.PrepareRequest(PublishedRequest request)
   at Umbraco.Web.UmbracoInjectedModule.ProcessRequest(HttpContextBase httpContext)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

Any idea how to prevent this from happening?
Thanks!

**Comment by Shazwazza** [comment]
Have you tried the latest version of Examine 1.x ? https://www.nuget.org/packages/Examine/1.2.2

**Comment by Sven883** [comment]
Hey @Shazwazza i'll give that a try. Thanks
