### ISSUE TITLE
"Queue empty" when rebuilding index

### ISSUE THREAD

**Issue by royberris** [Shazwazza/Examine#266]
Hello, I am trying to rebuild a (custom) index in an Umbraco website when the cache refresher for that component is called. We have a multi-tenant setup and I need the replica servers to rebuild when the data changes in the database. We have a custom index that is build for data that is outside Umbraco. I now get the exception "Queue empty". 

We need to do this because the search function on the website is outdated after the new data is synced to the database. 

_I saw a post suggesting to delete the `/App_Data/TEMP/ExamineIndex` folder and rebuild it. But that didn't work._

See stack trace below. Any idea what is going wrong here? 

```
System.InvalidOperationException: Queue empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Examine.LuceneEngine.OpenReaderTracker.CloseStaleReaders(Directory dir, TimeSpan ts) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\OpenReaderTracker.cs:line 56
   at Examine.LuceneEngine.Providers.LuceneIndex.EnsureIndex(Boolean forceOverwrite) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneIndex.cs:line 437
   at Examine.LuceneEngine.Providers.LuceneIndex.CreateIndex() in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneIndex.cs:line 507
   at Umbraco.Examine.IndexRebuilder.RebuildIndex(String indexName) in D:\a\1\s\src\Umbraco.Examine\IndexRebuilder.cs:line 43
   at Rembrandt.Umbraco8.Classes.UmbracoComponents.TombstoneCacheComponent.CacheUpdated(TombstoneCacheRefresher sender, CacheRefresherEventArgs eventArgs)
   at Umbraco.Core.Cache.CacheRefresherBase`1.OnCacheUpdated(TInstanceType sender, CacheRefresherEventArgs args) in D:\a\1\s\src\Umbraco.Core\Cache\CacheRefresherBase.cs:line 116
   at Umbraco.Core.Cache.CacheRefresherBase`1.RefreshAll() in D:\a\1\s\src\Umbraco.Core\Cache\CacheRefresherBase.cs:line 59
   at Umbraco.Core.Sync.ServerMessengerBase.DeliverLocal(ICacheRefresher refresher, MessageType messageType, IEnumerable`1 ids, String json) in D:\a\1\s\src\Umbraco.Core\Sync\ServerMessengerBase.cs:line 187
   at Umbraco.Core.Sync.ServerMessengerBase.Deliver(ICacheRefresher refresher, MessageType messageType, IEnumerable`1 ids, String json) in D:\a\1\s\src\Umbraco.Core\Sync\ServerMessengerBase.cs:line 314
   at Umbraco.Core.Sync.ServerMessengerBase.PerformRefreshAll(ICacheRefresher refresher) in D:\a\1\s\src\Umbraco.Core\Sync\ServerMessengerBase.cs:line 141
   at Umbraco.Web.Cache.DistributedCache.RefreshAll(Guid refresherGuid) in C:\Git werk\Umbraco sources\Umbraco-CMS\src\Umbraco.Web\Cache\DistributedCache.cs:line 134
```

**Comment by Shazwazza** [comment]
Please try the latest version of Examine in your current major version. Sounds like a bug that's already been fixed. What version are you using?

**Comment by royberris** [comment]
We are using Umbraco 8.17 which seems to come with Examine 1.2.0?

**Comment by Shazwazza** [comment]
Would be good to get Umbraco to ship with vLatest of Examine.   I've linked an issue.
