### ISSUE TITLE
System.NotSupportedException: 'Cannot convert search results to member instances'

### ISSUE THREAD

**Issue by deekoulos** [Shazwazza/Examine#292]
Hi there,

i am migrating from umbraco 8 to 10 and now i am facing this error:

```
System.NotSupportedException: 'Cannot convert search results to member instances'

   at Umbraco.Extensions.ExamineExtensions.ToPublishedSearchResults(IEnumerable`1 results, IPublishedSnapshot snapshot)
   at Feedbax.Core.Helpers.MemberHelper.GetMemberByReviewKey(String key, String[] fields) in C:\Users\armin\source\repos\Feedbax-Core\Feedbax.Core\Helpers\MemberHelper.cs:line 143
   at Feedbax.Core.Controllers.Render.SubmitReviewController.Index() in C:\Users\armin\source\repos\Feedbax-Core\Feedbax.Core\Controllers\Render\SubmitReviewController.cs:line 72
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
```

This exception is triggered by this peace of code which worked in u8:

```
var index = _indexHelper.GetMemberIndex();

        var booleanOperation = index.Searcher
            .CreateQuery("member")
            .ManagedQuery(key, fields);

var member = _publishedContentQuery.Search(booleanOperation, 0, int.MaxValue, out _)
            .Select(x => x.Content as Member)
            .Single();
```

key is a guid
fields is ["reviewItems"]

when i test the search query in umbraco backoffice > settings > examine management > member index:

`reviewItems:0122c909-34ea-4410-8523-e2f5688f7778`

i get the correct result, but this is not working in code for some reasons and seems to be a bug?

I also tried to make the search call even simpler as followed:

`var member2 = _publishedContentQuery.Search(booleanOperation, 0, int.MaxValue, out _);`

same exception.

using Umbraco 10.0.2 and Examine 3.0.1

**Comment by Shazwazza** [comment]
Hi, this is an Umbraco issue not an Examine one, you'll need to file the report on the Umbraco issue tracker. Thanks!
