### ISSUE TITLE
Failing unit tests (Examine.Test.Examine.Lucene.Search.FluentApiTests.Sort_Result_By_Double_Fields)

### ISSUE THREAD

**Issue by nikcio** [Shazwazza/Examine#305]
When running the unit tests locally I've experienced that two unit tests keep failing:

```
Failed Sort_Result_By_Double_Fields("fulltext",Double) [1 s]
  Error Message:
     Expected: 2.6000000000000001d
  But was:  5.0d

  Stack Trace:
     at Examine.Test.Examine.Lucene.Search.FluentApiTests.Sort_Result_By_Double_Fields(String fieldType, SortType sortType) in C:\Vertica\Github\misc\Examine\src\Examine.Test\Examine.Lucene\Search\FluentApiTests.cs:line 1385

  Failed Sort_Result_By_Double_Fields("fulltextsortable",Double) [1 s]
  Error Message:
     Expected: 2.6000000000000001d
  But was:  5.0d

  Stack Trace:
     at Examine.Test.Examine.Lucene.Search.FluentApiTests.Sort_Result_By_Double_Fields(String fieldType, SortType sortType) in C:\Vertica\Github\misc\Examine\src\Examine.Test\Examine.Lucene\Search\FluentApiTests.cs:line 1385
```

The weird thing is that they don't seem to be failing in the GitHub workflow. I see the two tests fail both in Visual Studio 2022 and when using `dotnet test`

Source code: https://github.com/Shazwazza/Examine/blob/9a26cecab9975659e2d06d8322152e753a9c55a5/src/Examine.Test/Examine.Lucene/Search/FluentApiTests.cs#L1313-L1369

Example in GitHub actions: https://github.com/Shazwazza/Examine/actions/runs/3297631605/jobs/5438680589#step:9:5658

**Comment by nikcio** [comment]
@nzdev That actually makes a ton of sense

**Comment by nzdev** [comment]
I'm not sure. On closer inspection, the values are way off
