### ISSUE TITLE
Indexer Error when trying to rebuild the index

### ISSUE THREAD

**Issue by samsur** [Shazwazza/Examine#60]
I have a simple console app to index the data from a SQL table.  I am receiving the following error

**Value cannot be null**
_at System.Web.Configuration.ProvidersHelper.InstantiateProvider(ProviderSettings providerSettings, Type providerType)
   at System.Web.Configuration.ProvidersHelper.InstantiateProviders(ProviderSettingsCollection configProviders, ProviderCollection providers, Type providerType)
   at Examine.ExamineManager.EnsureProviders() in X:\Projects\Examine\Examine\Projects\Examine\ExamineManager.cs:line 96
   at Examine.ExamineManager.get_IndexProviderCollection() in X:\Projects\Examine\Examine\Projects\Examine\ExamineManager.cs:line 72_

on this line : ExamineManager.Instance.IndexProviderCollection["Simple2Indexer"].RebuildIndex();

Here is what My app.config looks like

```
<configSections>
    <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
    <section name="Examine" type="Examine.Config.ExamineSettings, Examine" requirePermission="false" />
    <section name="ExamineLuceneIndexSets" type="Examine.LuceneEngine.Config.IndexSets, Examine" requirePermission="false" />

  </configSections>

  <Examine RebuildOnAppStart="false">
    <ExamineIndexProviders>
      <providers>
        <add name="Simple2Indexer" type="Examine.LuceneEngine.Providers.SimpleDataIndexer, Examine" dataService="LucenePOC.Data.ForumDataReaderService,LucenePOC.Data"  indexTypes="TestType" runAsync="false"/>
        <add name="SecondIndexer" type="Examine.LuceneEngine.Providers.SimpleDataIndexer, Examine" dataService="LucenePOC.Data.ForumDataReaderService,LucenePOC.Data" indexTypes="TestType2" runAsync="false"/>
      </providers>
    </ExamineIndexProviders>
    <ExamineSearchProviders defaultProvider="Simple2Searcher">
      <providers>
        <add name="Simple2Searcher" type="Examine.LuceneEngine.Providers.LuceneSearcher, Examine"  />
        <add name="MultiIndexSearcher" type="Examine.LuceneEngine.Providers.MultiIndexSearcher, Examine"
         indexSets="Simple2IndexSet,SecondIndexSet" />
      </providers>
    </ExamineSearchProviders>
  </Examine>
  <ExamineLuceneIndexSets>
    <IndexSet SetName="Simple2IndexSet" IndexPath="F:\Temp\Examine\SimpleIndexSet2">
      <IndexUserFields>
        <add Name="Id" />
        <add Name="Link" />
        <add Name="Module" />
        <add Name="Section" />
        <add Name="Message" />
        <add Name="CreatedBy" />
        <add Name="CreatedOn" />
        <add Name="ModifiedBy" />
        <add Name="ModifiedOn" />
      </IndexUserFields>
    </IndexSet>
    <IndexSet SetName="SecondIndexSet" IndexPath="F:\Temp\Examine\SimpleIndexSet2">
      <IndexUserFields>
        <add Name="Id" />
        <add Name="Link" />
        <add Name="Module" />
        <add Name="Section" />
        <add Name="Message" />
        <add Name="CreatedBy" />
        <add Name="CreatedOn" />
        <add Name="ModifiedBy" />
        <add Name="ModifiedOn" />
      </IndexUserFields>
    </IndexSet>
  </ExamineLuceneIndexSets>

```
My Package.config looks like this
```
<packages>
  <package id="EntityFramework" version="6.1.3" targetFramework="net452" />
  <package id="Examine" version="0.1.70.0" targetFramework="net452" />
  <package id="Lucene.Net" version="2.9.4.1" targetFramework="net452" />
  <package id="SharpZipLib" version="0.86.0" targetFramework="net452" />
</packages>
```

Can you please let me know, what I am missing? Thanks

**Comment by samsur** [comment]
I found out that the issue  was caused by my oversight. The assembly name was incorrect
 instead of LucenePOC.Data it should have been LucensePOC.. my mistake

**Comment by Shazwazza** [comment]
Sorry for the delay but I'm glad you figured it out :)
