### ISSUE TITLE
v0.1.84 upgrade casues YSOD

### ISSUE THREAD

**Issue by Jeavon** [Shazwazza/Examine#88]
I've been debugging this exception gut I can't quite figure it.

With v0.1.84 I get the following exception:

```
[NullReferenceException: Object reference not set to an instance of an object.]
   Examine.OrderedDictionary`2.System.Collections.Generic.IDictionary<TKey,TVal>.set_Item(TKey key, TVal value) in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\OrderedDictionary.cs:89
   Examine.LuceneEngine.SearchResults.PrepareSearchResult(SearchResult sr, Document doc) in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\SearchResults.cs:207
   Examine.LuceneEngine.<Skip>d__26.MoveNext() in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\SearchResults.cs:253
   System.Linq.Enumerable.FirstOrDefault(IEnumerable`1 source) +145
   Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedMediaCache.GetUmbracoMediaCacheValues(Int32 id) +749
   Umbraco.Core.Cache.<>c__DisplayClass1.<GetSafeLazy>b__0() +27
```
Switching back to v0.1.83 and this exception doesn't occur so I'm pretty sure this is caused by #85 but I can't seem to pin down exactly why...??

**Comment by robgha01** [comment]
We have the exact same problem as above i went back to 0.1.83 here is the message we get:
```
2017-07-28 17:01:17,757 [P50936/D9/T167] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.NullReferenceException: Objektreferensen har inte angetts till en instans av ett objekt.
   vid Umbraco.Core.Cache.HttpRequestCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem)
   vid BlueLeet.UCodeFirst.Helpers.UCodeFirstHelper.TypedContent(IPublishedContent publishedContent)
   vid BlueLeet.UCodeFirst.UCodeFirstApplicationEventHandler.PublishedContentRequestPrepared(Object sender, EventArgs e)
   vid Umbraco.Web.Routing.PublishedContentRequest.OnPrepared()
   vid Umbraco.Web.Routing.PublishedContentRequestEngine.PrepareRequest()
   vid Umbraco.Web.UmbracoModule.ProcessRequest(HttpContextBase httpContext)
   vid System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   vid System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
 2017-07-28 17:06:10,259 [P50936/D9/T217] WARN  umbraco.macro - Error loading partial view macro (View: ~/Views/MacroPartials/WidgetVector.cshtml). Exception: System.Exception: Exception while creating a value. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Examine.OrderedDictionary`2.System.Collections.Generic.IDictionary<TKey,TVal>.set_Item(TKey key, TVal value) in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\OrderedDictionary.cs:line 89
   at Examine.LuceneEngine.SearchResults.PrepareSearchResult(SearchResult sr, Document doc) in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\SearchResults.cs:line 207
   at Examine.LuceneEngine.SearchResults.<Skip>d__26.MoveNext() in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\SearchResults.cs:line 253
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedMediaCache.GetUmbracoMediaCacheValues(Int32 id)
   at Umbraco.Core.Cache.DictionaryCacheProviderBase.<>c__DisplayClass1.<GetSafeLazy>b__0()
   --- End of inner exception stack trace ---
   at Umbraco.Core.Cache.HttpRuntimeCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, CacheDependency dependency)
   at Umbraco.Core.Cache.HttpRuntimeCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, String[] dependentFiles)
   at Umbraco.Core.Cache.DeepCloneRuntimeCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, String[] dependentFiles)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedMediaCache.GetCacheValues(Int32 id, Func`2 func)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedMediaCache.GetUmbracoMedia(Int32 id)
   at Umbraco.Web.PublishedCache.ContextualPublishedCache`1.GetById(Boolean preview, Int32 contentId)
   at Umbraco.Web.UmbracoHelper.TypedMediaForObject(Object id)
   at BlueLeet.UCodeFirst.Converters.PublishedContentConverter.Read(PropertyInfo propertyInfo, Object value)
   at Castle.Proxies.Invocations.IConverter_Read.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at BlueLeet.UCodeFirst.Proxy.Converter.Interceptors.ProfileConverterInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IConverterProxy_2.Read(PropertyInfo propertyInfo, Object value)
   at BlueLeet.UCodeFirst.Proxy.MacroType.Interceptors.MacroPropertyGetInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.WidgetVectorMacroTypeProxy.get_Vector()
   at ASP._Page_Views_MacroPartials_WidgetVector_cshtml.Execute() in d:\Workspaces\BlueLeet\Websites\SpecialistPortalen\SpecialistPortalen.UI\Views\MacroPartials\WidgetVector.cshtml:line 4
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at Umbraco.Web.Mvc.ControllerExtensions.RenderViewResultAsString(ControllerBase controller, ViewResultBase viewResult)
   at Umbraco.Web.Macros.PartialViewMacroEngine.Execute(MacroModel macro, IPublishedContent content)
   at umbraco.macro.LoadPartialViewMacro(MacroModel macro)
   at umbraco.macro.renderMacro(Hashtable pageElements, Int32 pageId)
 2017-07-28 17:06:10,260 [P50936/D9/T217] WARN  umbraco.macro - Error loading Partial View (file: ~/Views/MacroPartials/WidgetVector.cshtml). Exception: System.Exception: Exception while creating a value. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Examine.OrderedDictionary`2.System.Collections.Generic.IDictionary<TKey,TVal>.set_Item(TKey key, TVal value) in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\OrderedDictionary.cs:line 89
   at Examine.LuceneEngine.SearchResults.PrepareSearchResult(SearchResult sr, Document doc) in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\SearchResults.cs:line 207
   at Examine.LuceneEngine.SearchResults.<Skip>d__26.MoveNext() in C:\Users\Shannon\Documents\_Projects\Examine\Examine\src\Examine\LuceneEngine\SearchResults.cs:line 253
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedMediaCache.GetUmbracoMediaCacheValues(Int32 id)
   at Umbraco.Core.Cache.DictionaryCacheProviderBase.<>c__DisplayClass1.<GetSafeLazy>b__0()
   --- End of inner exception stack trace ---
   at Umbraco.Core.Cache.HttpRuntimeCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, CacheDependency dependency)
   at Umbraco.Core.Cache.HttpRuntimeCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, String[] dependentFiles)
   at Umbraco.Core.Cache.DeepCloneRuntimeCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem, Nullable`1 timeout, Boolean isSliding, CacheItemPriority priority, CacheItemRemovedCallback removedCallback, String[] dependentFiles)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedMediaCache.GetCacheValues(Int32 id, Func`2 func)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedMediaCache.GetUmbracoMedia(Int32 id)
   at Umbraco.Web.PublishedCache.ContextualPublishedCache`1.GetById(Boolean preview, Int32 contentId)
   at Umbraco.Web.UmbracoHelper.TypedMediaForObject(Object id)
   at BlueLeet.UCodeFirst.Converters.PublishedContentConverter.Read(PropertyInfo propertyInfo, Object value)
   at Castle.Proxies.Invocations.IConverter_Read.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at BlueLeet.UCodeFirst.Proxy.Converter.Interceptors.ProfileConverterInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IConverterProxy_2.Read(PropertyInfo propertyInfo, Object value)
   at BlueLeet.UCodeFirst.Proxy.MacroType.Interceptors.MacroPropertyGetInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.WidgetVectorMacroTypeProxy.get_Vector()
   at ASP._Page_Views_MacroPartials_WidgetVector_cshtml.Execute() in d:\Workspaces\BlueLeet\Websites\SpecialistPortalen\SpecialistPortalen.UI\Views\MacroPartials\WidgetVector.cshtml:line 4
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at Umbraco.Web.Mvc.ControllerExtensions.RenderViewResultAsString(ControllerBase controller, ViewResultBase viewResult)
   at Umbraco.Web.Macros.PartialViewMacroEngine.Execute(MacroModel macro, IPublishedContent content)
   at umbraco.macro.LoadPartialViewMacro(MacroModel macro)
   at umbraco.macro.renderMacro(Hashtable pageElements, Int32 pageId)
 2017-07-28 17:06:10,288 [P50936/D9/T212] WARN  umbraco.macro - Error loading partial view macro (View: ~/Views/MacroPartials/Form.cshtml). Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Core.Cache.HttpRequestCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem)
   at BlueLeet.UCodeFirst.Helpers.UCodeFirstHelper.TypedContent(IPublishedContent publishedContent)
   at Castle.Proxies.Invocations.IConverter_Read.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at BlueLeet.UCodeFirst.Proxy.Converter.Interceptors.ProfileConverterInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IConverterProxy_1.Read(PropertyInfo propertyInfo, Object value)
   at BlueLeet.UCodeFirst.Proxy.MacroType.Interceptors.MacroPropertyGetInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.FormMacroTypeProxy.get_Form()
   at ASP._Page_Views_MacroPartials_Form_cshtml.Execute() in d:\Workspaces\BlueLeet\Websites\SpecialistPortalen\SpecialistPortalen.UI\Views\MacroPartials\Form.cshtml:line 3
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at Umbraco.Web.Mvc.ControllerExtensions.RenderViewResultAsString(ControllerBase controller, ViewResultBase viewResult)
   at Umbraco.Web.Macros.PartialViewMacroEngine.Execute(MacroModel macro, IPublishedContent content)
   at umbraco.macro.LoadPartialViewMacro(MacroModel macro)
   at umbraco.macro.renderMacro(Hashtable pageElements, Int32 pageId)
 2017-07-28 17:06:10,288 [P50936/D9/T212] WARN  umbraco.macro - Error loading Partial View (file: ~/Views/MacroPartials/Form.cshtml). Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Core.Cache.HttpRequestCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem)
   at BlueLeet.UCodeFirst.Helpers.UCodeFirstHelper.TypedContent(IPublishedContent publishedContent)
   at Castle.Proxies.Invocations.IConverter_Read.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at BlueLeet.UCodeFirst.Proxy.Converter.Interceptors.ProfileConverterInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IConverterProxy_1.Read(PropertyInfo propertyInfo, Object value)
   at BlueLeet.UCodeFirst.Proxy.MacroType.Interceptors.MacroPropertyGetInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.FormMacroTypeProxy.get_Form()
   at ASP._Page_Views_MacroPartials_Form_cshtml.Execute() in d:\Workspaces\BlueLeet\Websites\SpecialistPortalen\SpecialistPortalen.UI\Views\MacroPartials\Form.cshtml:line 3
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at Umbraco.Web.Mvc.ControllerExtensions.RenderViewResultAsString(ControllerBase controller, ViewResultBase viewResult)
   at Umbraco.Web.Macros.PartialViewMacroEngine.Execute(MacroModel macro, IPublishedContent content)
   at umbraco.macro.LoadPartialViewMacro(MacroModel macro)
   at umbraco.macro.renderMacro(Hashtable pageElements, Int32 pageId)
```

**Comment by Shazwazza** [comment]
damn ok ill investigate

**Comment by Shazwazza** [comment]
Fixed and released https://github.com/Shazwazza/Examine/releases/tag/v0.1.85
